### ISSUE TITLE
Integrate PDF to Foundry data

### ISSUE THREAD

**Issue by DawidIzydor** [deidril/pf2-pdf-en-import#11]
This is a great tool for importing the newer PDFs however it lacks the support for older ones. PDF to Foundry module is not updated and does not work with V10. Integrate its data into this module to have full import support in one place

**Comment by deidril** [comment]
Hello,

unfortunaly, i don't have pdf2foundry datas :( While some of them could be retrieved, a lot more seems to be crypted. 

Also, pdf2foundry author said he will deliver a v10 version of his module, so the need to merge these datas seems a useless work at this point.

**Comment by knro** [comment]
@deidril It's not useless because we don't know if he can delivery v10 anytime soon. I've been looking to import  "Troubles in Otari" PDF and it's unfortunate no system today can do this :(

**Comment by deidril** [comment]
pdf2foundry has been updated to v10. Issue closed
