### ISSUE TITLE
Shadows at Sundown import hangs on 47/97

### ISSUE THREAD

**Issue by eddiephlash** [deidril/pf2-pdf-en-import#20]
This is happening reliably, regardless of whether I check the "Use content generated through MidJourney"

![image](https://user-images.githubusercontent.com/8182048/212090484-27ce1645-d199-4c5e-aa79-7ec6c4582609.png)

**Comment by deidril** [comment]
Hi, which version of the module did you used ?

**Comment by deidril** [comment]
I released a new version of the module. V1.20. could you try with this version ?

**Comment by eddiephlash** [comment]
I was on V1.19.

Tried V1.20 just now, and it looks like the import was successful! Thanks for the super fast turnaround, and I also like the new gui!

**Comment by deidril** [comment]
Closing the issue then :)
