### ISSUE TITLE
Episode 04 : To Seek the Heart of Calamity not recognized

### ISSUE THREAD

**Issue by FerrusR** [deidril/pf2-pdf-en-import#24]
Not sure what I'm missing but if I try to import I get "File couldn't be identified" window.
Foundry: v10, build 291
PF2e system version 4.6.8
Module version 1.22
Scenario bought and downloaded from official Paizo store.
No errors in log.

Also tried creating empty world with no modules besides this one to make sure it's not module conflict. Still not recognized.
And I also tried importing S4E1 and S4E2 (the only other scenarios that I own) and they worked fine.

**Comment by deidril** [comment]
Hello, i'll look this problem asap.

**Comment by deidril** [comment]
Hello, the problem cames that i used the beta version for the pdf. I have to fix the import and it should be ok in a few day.

**Comment by deidril** [comment]
Hello, it should be fixed with today's release

**Comment by FerrusR** [comment]
Tested and now it works. Thank you!
