### ISSUE TITLE
Module Shows in Non-Pathfinder Worlds

### ISSUE THREAD

**Issue by Vhostym-the-Sojourner** [deidril/pf2-pdf-en-import#26]
The module shows in the management section of worlds that are not Pathfinder.  Can the manifest be updated to restrict the module to Pathfinder-2e only?

Thanks!

**Comment by deidril** [comment]
Sure, I'll update the manifest

**Comment by Vhostym-the-Sojourner** [comment]
Thank you!

**Comment by deidril** [comment]
Should be fixed in today's release.

**Comment by Vhostym-the-Sojourner** [comment]
Thank you for fixing this! I have confirmed it no longer shows in other system worlds.
