### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by vampiregoat699** [deidril/pf2-pdf-en-import#28]
I bought the PDFs from Humble bundle and this will not work with their books even though they are legit

**Comment by deidril** [comment]
Hi, the pdfs from the last humble bundle aren't in the list of the support
pdf. See the 'supported pdfs' list in the module interface, or here :
https://github.com/deidril/pf2-pdf-en-import/blob/master/README.md

Le sam. 4 févr. 2023 à 21:00, vampiregoat699 ***@***.***> a
écrit :
