### ISSUE TITLE
Feature Request: Secret 9th Dark Archive Adventure, In Darkness.

### ISSUE THREAD

**Issue by Kalnix** [deidril/pf2-pdf-en-import#39]
As a reward for the Dark Archives ARG that Paizo put out, there was a secret 9th Dark Archive adventure called In Darkness.

The PDF is free to download from the Paizo website, though a bit hidden. You can download it from https://paizo.com/products/btq02d8j?Pathfinder-Dark-Archive and then scolling down to Additional Web Content Spoiler and clicking it. This will then show Solution to Additional Web Content and if you click that there will be a download link for In Darkness. This is the final casefile that ties all the other 8 casefiles together.

**Comment by deidril** [comment]
It'll be available for import very soon :)
