### ISSUE TITLE
Bug Report: PDF Import Stuck on 'Meliosa's Leshy' Every Attempt

### ISSUE THREAD

**Issue by GorgoPrimus** [deidril/pf2-pdf-en-import#47]
![Untitled](https://github.com/deidril/pf2-pdf-en-import/assets/126842722/93e420ae-98ef-4477-98df-7c836298e4df)

**Comment by deidril** [comment]
Indeed.

The import works with pf2e system 5.4.1 but not with 5.4.4.

Thank for reporting. I'll add the bug fix asap.

**Comment by deidril** [comment]
Fixed in the last release
