### ISSUE TITLE
PDFs Not Recognized

### ISSUE THREAD

**Issue by EightFiveZeroEight** [deidril/pf2-pdf-en-import#5]
None of the following Paizo PDFS work:

- Pathfinder Second Edition Core Rulebook
- Pathfinder Second Edition Bestiary
- Pathfinder Lost Omens World Guide
- Pathfinder Advanced Player's Guide
- Pathfinder Lost Omens Character Guide
- Shadows of the Ancients (Strength of Thousands 6 of 6)
- Pathfinder Adventure: Threshold of Knowledge
- Pathfinder Society Scenario: Echoes of Desperation
- Pathfinder Flip-Mat: Shipwrecks
- Pathfinder Lost Omens: The Mwangi Expanse
- Pathfinder Adventure Path: Hurricane's Howl (Strength of Thousands 3 of 6)
- Secrets of the Temple-City (Strength of Thousands 4 of 6)
- Doorway to the Red Star (Strength of Thousands 5 of 6)
- Pathfinder Adventure: The Slithering
- Pathfinder Flip-Mat: The Slithering
- Pathfinder Society Scenario: Star-Crossed Voyages
- Pathfinder Society Scenario: The Lost Legend
- Pathfinder Society Scenario: The Star-Crossed Court
- Pathfinder Flip-Mat: Forest Multi-Pack
- Pathfinder Flip-Mat: Ambush Sites Multi-Pack
- Pathfinder Adventure Path: Kindled Magic (Strength of Thousands 1 of 6)
- Pathfinder Adventure Path: Spoken on the Song Wind (Strength of Thousands 2 of 6)
- Pathfinder Bounty: Fishing in Anthusis
- Pathfinder Bounty: Sodden Stories
- Pathfinder Flip-Mat: Docks
- Pathfinder Flip-Mat: Jungle Multi-Pack
- Pathfinder Second Edition GM Screen
- Pathfinder Character Sheet Pack

**Comment by deidril** [comment]
Use PDF2Foundry module for Strength of Thousand, Bounties and Pathfinder Society Scenarios.

There is no short term plan for the import of the listed pdfs
