### ISSUE TITLE
Token setting error

### ISSUE THREAD

**Issue by Veemo590** [deidril/pf2-pdf-en-import#50]
New to this so hopefully all info!

so when using an imported token/actor in this case Little trouble in big absolom. all added tokens/actors have this issue

 All modules off, foundry v11 build 311  pf2e 5.6.1   error when selecting the settings button on a token.  when pressing it nothing happens but i can no longer select the token, cant delete, move etc.
error message:
![image](https://github.com/deidril/pf2-pdf-en-import/assets/146487367/5d3865c9-30a1-4e5e-8033-98b6155eb7f7)

somehow it has no flags (from what I've been told!)
![image](https://github.com/deidril/pf2-pdf-en-import/assets/146487367/053e1d89-4f06-4842-8308-d9ab08b25fc9)

non imported actors don't have this issue
duplicated actors don't have this issue either.

**Comment by deidril** [comment]
Thank for the detailled report. I was able to quickly found the problem.
It will be fixed in a very soon emergency update.

**Comment by deidril** [comment]
Should be fixed in today's emergency release.

**Comment by deidril** [comment]
Fixed in last releae. Reopen another issue if it happens again :)
