### ISSUE TITLE
Import for Crown of the Kobold King is broken

### ISSUE THREAD

**Issue by Gwearn** [deidril/pf2-pdf-en-import#62]
Progresses to step 189/201 "Created Journal 00 Adventure Toolbox" and freezes, giving two errors in the console.

Cannot read properties of undefined (reading '0') foundry.js:68326:78
    fetch foundry.js:68326
    notify foundry.js:68223
    error foundry.js:68260
    _handleError foundry.js:3468
    dispatch foundry.js:3450
    value socket.js:532
    value socket.js:459
    emit index.mjs:136
    value manager.js:207

Uncaught (in promise) Error: Cannot read properties of undefined (reading '0')
foundry.js:3466:46

This is on a fresh new world with no other modules enabled.

**Comment by deidril** [comment]
Hello, 

retested with a new world, with system 5.14.4 and 5.15.0, and everything worked fine.
I redownloaded the pdf and retried with blank world and 5.15 and again, everything worked fine.

The only advice i can give you is to redownload the pdf from paizo. It happens some reader softwares modify pdfs and make them unable to work with the module.

**Comment by Gwearn** [comment]
After a whole bunch of troubleshooting, I figured it out:
The problem was my ubuntu server. It doesn't have a PDF reader, and I was getting font errors. I installed foundry on my Windows PC, created the world there, and exported it to my server without issue.
