### ISSUE TITLE
Enhancement: Allow Flip Map Imports to Import in Portrait

### ISSUE THREAD

**Issue by avagdumortesin** [deidril/pf2-pdf-en-import#63]
When importing a PDF of a PFS scenario, the map is always imported in landscape; I would like to see a setting to change this to have the map imported in the orientation shown in the scenario. While some people may like having the map in landscape to match their monitor orientation, I believe that many people would prefer to have it shown in the standard orientation.

At the very least, the map should be imported so that North is up, as that is what is standard.

**Comment by deidril** [comment]
Hello,
can you tell me which PFS has a bugged map ?

**Comment by avagdumortesin** [comment]
I thought there were more, but I may not have the worlds anymore. These are the two that I found:
4-02 (imported July 2023)
Q14 (imported January 2024; this map was also damaged)

**Comment by deidril** [comment]
Ok, i'll look at this.

**Comment by deidril** [comment]
i think it was solved in previous releases.
