### ISSUE TITLE
[Issue] Crown of the Kobold King import

### ISSUE THREAD

**Issue by Malkyn99** [deidril/pf2-pdf-en-import#64]
Title. The import stalls on Jekkajak. Fresh download from the Paizo store, so it's watermarked and up to date.

**Comment by deidril** [comment]
It seems the 'Red Kobold Dragon Mage' has been renamed or deleted from the compendiums with the late changes in monster manuals. I'll look at this.

Another way is to import the pdf with a 14.x system version and then update your system to 15.x .
