### ISSUE TITLE
Support for Quest 18

### ISSUE THREAD

**Issue by dtread14** [deidril/pf2-pdf-en-import#66]
Hi, thanks for all the hard work here.

I'm wondering if Quest 18 is in the works? I'm planning to run it on 5/18.  If not, I can prep myself of course, but if by chance it will be out by then all the better.  Thanks!

**Comment by deidril** [comment]
Hi, quest #18 import won't be released in May :/

**Comment by deidril** [comment]
Quest 18 is now supported.
