### ISSUE TITLE
broken for extinction curse chapter 2 and 6

### ISSUE THREAD

**Issue by sakulstra** [deidril/pf2-pdf-en-import#67]
Hello, I just tried this module and first of - it's awesome!

That said, i faced some issues with chapter 2 and 6.
On both i see sth like:
```
Error: ScenePF2e validation errors:
  walls: 
    LBOgFOT7FixeUjYd: 
      move: 1 is not a valid choice
      sound: 1 is not a valid choice
    hJ2nZuQCEeI7EW7o: 
      move: 1 is not a valid choice
      sound: 1 is not a valid choice
    xiSda1DXsuG3BHuR: 
      move: 1 is not a valid choice
      sound: 1 is not a valid choice
    E3QxLHqKiQrJpUGo: 
      move: 1 is not a valid choice
      sound: 1 is not a valid choice
```
in my console.

Using foundry 12, which might be part of the problem, but rest has worked just fine.

**Comment by deidril** [comment]
Hi, 
I think you are using PDF2Foundry , not my module. 

Mine doesn't support extinction curse, but PDF2foundry does.

**Comment by sakulstra** [comment]
@deidril uhh sorry you're right. confused the names :/
