### ISSUE TITLE
Import not working for Little Trouble in Big Absalom

### ISSUE THREAD

**Issue by nickkeane** [deidril/pf2-pdf-en-import#72]
It gets stuck at Madame Trunchsnuffle during import process.

PF2e: v6.5.0
FVTT: v12.331
Importer: v4.61

<img width="319" alt="image" src="https://github.com/user-attachments/assets/24c4d03e-4766-4505-8eeb-86bc8848be39">

**Comment by DawidIzydor** [comment]
Same issue here, tested on an empty world, getting this error:

`simeek.actor.webp saved to helyx/little-trouble-in-big-absalom/actors [foundry.js:70651:22](https://foundry.dawid-izydor.pl/scripts/foundry.js)
simeek.token.webp saved to helyx/little-trouble-in-big-absalom/actors [foundry.js:70651:22](https://foundry.dawid-izydor.pl/scripts/foundry.js)
Uncaught (in promise) TypeError: d is null
    #preCreateDocumentArray https://foundry.dawid-izydor.pl/scripts/foundry-esm.js:56315
    _createDocuments https://foundry.dawid-izydor.pl/scripts/foundry-esm.js:56275
    create https://foundry.dawid-izydor.pl/scripts/foundry-esm.js:12264
    createDocuments https://foundry.dawid-izydor.pl/scripts/foundry-esm.js:11407
    create https://foundry.dawid-izydor.pl/scripts/foundry-esm.js:11550
    #import_actor https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #import_entry_step3 https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #import_entry https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #import_entries https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    async* https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    do_start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0xe0b752 https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0x21d80b https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*state https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    proceed https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #run https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    do_start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0xe0b752 https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0x21d80b https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*state https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    proceed https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    import_folders https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*#import_folders https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    do_start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0xe0b752 https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0x21d80b https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*state https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    proceed https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #prepare https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    <anonymous> https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    do_start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0xe0b752 https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0x21d80b https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*state https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    proceed https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    load_items https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #load_items https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    <anonymous> https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    do_start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0xe0b752 https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    start https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0x21d80b https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*state https://foundry.dawid-izydor.pl/modules/pf2-pdf-en-import/src/helyx.bundle.js:1`

**Comment by deidril** [comment]
confirmed. Dragon Faery renamed Fey Dragonet in remaster.

**Comment by deidril** [comment]
Fixed for next release

**Comment by deidril** [comment]
Fixed and released
