### ISSUE TITLE
Import for The Enmity Cycle stops with an error

### ISSUE THREAD

**Issue by Hddeenn** [deidril/pf2-pdf-en-import#73]
The import process throws an error and halts when creating the actor "Elite Sand Wolf." This was tested on an empty world.
PF2e: v6.6.1
FVTT: v12.331
Importer: v4.61

Error:
Uncaught (in promise) TypeError: d is null
    #preCreateDocumentArray host/scripts/foundry-esm.js:56387
    _createDocuments host/scripts/foundry-esm.js:56347
    create host/scripts/foundry-esm.js:12281
    createDocuments host/scripts/foundry-esm.js:11423
    create host/scripts/foundry-esm.js:11567
    #import_actor host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #import_entry_step3 host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #import_entry host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #import_entries host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    async* host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    do_start host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0xe0b752 host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    start host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0x21d80b host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*state host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    proceed host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #run host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    do_start host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0xe0b752 host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    start host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0x21d80b host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*state host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    proceed host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    import_folders host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*#import_folders host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    do_start host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0xe0b752 host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    start host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0x21d80b host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*state host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    proceed host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #prepare host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    <anonymous> host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    do_start host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0xe0b752 host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    start host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    _0x21d80b host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    promise callback*state host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    proceed host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    load_items host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    #load_items host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
    <anonymous> host/modules/pf2-pdf-en-import/src/helyx.bundle.js:1
foundry-esm.js:56387:80

![Helyx Import Error the-enmity-cycle Elite Sand Wolf](https://github.com/user-attachments/assets/bb28cfb2-170f-4354-8b40-a1fa96c18770)

**Comment by deidril** [comment]
Fixed and released.
