### ISSUE TITLE
Error on PF2e One Shot

### ISSUE THREAD

**Issue by lpres468** [deidril/pf2-pdf-en-import#74]
I received the attached error when attempting to load "The Arclord Who Never Was". I loaded with no other modules on foundry and through Forge. Both got stuck at 34/50 (Animated Leather Armor).

![image](https://github.com/user-attachments/assets/612608c1-7a3b-44c8-8db9-d5a6d41e564d)

**Comment by deidril** [comment]
bug confirmed

**Comment by deidril** [comment]
Fixed ans released
