### ISSUE TITLE
Support for The Great Toy Heist

### ISSUE THREAD

**Issue by jkaplowitz** [deidril/pf2-pdf-en-import#75]
Hello,

Thanks for your great import tool. When you have time, it would be great if this tool could support importing The Great Toy Heist, Paizo's newest Free RPG Day adventure which was published in June:

https://paizo.com/products/btq03kph?Pathfinder-Free-RPG-Day-Adventure-The-Great-Toy-Heist

I know you're developing this module as a volunteer as time permits, and that due to the anti-piracy obfuscation there's no way for me to do the work and send you a pull request, so I understand this might need to wait until you have time. No pressure.

Thank you.

**Comment by deidril** [comment]
hi, i won't add any imports to the module soon ( or later ), only supporting what is already done.

**Comment by jkaplowitz** [comment]
Just noting for anyone who sees the previous history of this issue and who might infer from it that The Great Toy Heist is still not supported: the support was added some time after my issue was closed. Thanks for adding it!
